import os
## Model variables ##

# Training parameters
LABEL_COL_NAME = "labels"
PREDICTION_COL_NAME = "predict"
RANDOM_STATE = 42
VAL_SIZE = 0.2
TEST_SIZE = 0.25


## Filepaths and filenames ##

# Pretrained filenames
CONFIG_PRETRAINED_FILE = "config.json"
VOCAB_PRETRAINED_FILE = "vocab"
WEIGHTS_PRETRAINED_FILE = "weights"
SP_MODEL_FILE = "spm.model"

# GCS File paths
PRETRAINED_GCS_FOLDER = "pretrained/{}"
LM_FORWARD_FOLDER = "forward"
LM_BACKWARD_FOLDER = "backward"
SPM_FOLDER = "spm"
DATASET_GCS_PATH = os.path.join(PRETRAINED_GCS_FOLDER, "{}")
CONFIG_GCS_PATH = os.path.join(PRETRAINED_GCS_FOLDER, "{}", CONFIG_PRETRAINED_FILE)
VOCAB_GCS_PATH = os.path.join(PRETRAINED_GCS_FOLDER, "{}", f"{VOCAB_PRETRAINED_FILE}.pkl")
WEIGHTS_GCS_PATH = os.path.join(PRETRAINED_GCS_FOLDER, "{}", f"{WEIGHTS_PRETRAINED_FILE}.pth")
SP_MODEL_GCS_PATH = os.path.join(PRETRAINED_GCS_FOLDER, SPM_FOLDER, SP_MODEL_FILE)

# Local Filenames
MODELS_LOCAL_FOLDER = "models" 
DATASET_LOCAL_PATH = os.path.join(MODELS_LOCAL_FOLDER, "{}")
CONFIG_LOCAL_PATH = os.path.join(MODELS_LOCAL_FOLDER, CONFIG_PRETRAINED_FILE)
VOCAB_LOCAL_PATH = os.path.join(MODELS_LOCAL_FOLDER, f"{VOCAB_PRETRAINED_FILE}.pkl")
WEIGHTS_LOCAL_PATH = os.path.join(MODELS_LOCAL_FOLDER, f"{WEIGHTS_PRETRAINED_FILE}.pth")
SP_MODEL_LOCAL_PATH = os.path.join(MODELS_LOCAL_FOLDER, SP_MODEL_FILE)
LM_MODEL_PATH = "."
BESTMODEL_NAME = "bestmodel"
BESTMODEL_NAME_UNF = "bestmodel_unf"
ENCODER_FILE_NAME = "encoder"
